### ISSUE TITLE
Seek API documentation about tekscope instrument

### ISSUE THREAD

**Issue by Johnzjy** [amcdawes/VISA#1]
Hi sir:
     I found your repositorys that have script to control instrument. it help me to control my lab instruments. 
    Now,I have some problems . I cant find the python api of Tekscope  . Your code command can work,like 'WFMPRE:YMULT?'，'WFMPRE:YZERO?'.
    Could you please tell me the source of command ? if you have web link is better, I can download file by myself.
     Look forward to your reply. Thank you  a lot!

**Comment by amcdawes** [comment]
That command is a standard tektronix command just like we’d use via gpib or
other visa inferface. You can find them in the programmer manuals. For TDS
scopes this is here:

https://www.tek.com/manual/tds-family-programmer-manual
